version: "3.9"
services:
  server:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/usr/src/app/
      networks:
        - my_network
      links:
        - pgdb:pgdb
      environment:
        - POSTGRES_NAME=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - 8000:8000
      depends_on:
        - pgdb
  pgdb:
      image: postgres
      networks:
        - my_network
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      container_name: pgdb
      volumes:
        - pgdbdata:/var/lib/postgresql/data/
      ports:
        - 5432:5432
volumes:
  pgdbdata: null
networks:
  my_network:
    driver: bridge
