# Generated by Django 4.2.5 on 2023-12-20 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('AdressText', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NumberOfRooms', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NumberOfFloors', models.IntegerField(default=1)),
                ('NumberOfEntrances', models.IntegerField(default=1)),
                ('AdressID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.adress')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('ApplicationID', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.BooleanField(default=False)),
                ('ApartmentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.apartment')),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='HouseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.house'),
        ),
    ]
