# Generated by Django 4.2.5 on 2023-12-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adress',
            table='adress',
        ),
        migrations.AlterModelTable(
            name='apartment',
            table='apartment',
        ),
        migrations.AlterModelTable(
            name='application',
            table='application',
        ),
        migrations.AlterModelTable(
            name='house',
            table='house',
        ),
    ]
