# Generated by Django 4.2.5 on 2023-12-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_apartment_houseid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='Cost',
            field=models.FloatField(default=0),
        ),
    ]
