# Generated by Django 4.2.5 on 2023-12-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_apartment_image_alter_house_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='ApartmentNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='house',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
