# Generated by Django 4.2.5 on 2024-05-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_apartment_model3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='Area',
            field=models.FloatField(default=0, null=True),
        ),
    ]
