# Generated by Django 4.2.5 on 2024-05-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_apartment_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='Is_Booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='House_Number',
            field=models.IntegerField(default=0),
        ),
    ]
